version: "3.2"
services:
  redis:
    image: "redis:alpine@sha256:6833ca04ec87a2222928157125dffcca22c68e2db304164cc050ee9cc6b05b4e"
    command: ["redis-server", "/redis.conf"]
    ports:
    - "6379:6379"
    volumes:
    - $PWD/redis-data:/var/lib/redis
    - $PWD/conf/redis.conf:/redis.conf
    networks:
      node_net:
        ipv4_address: 172.28.1.2
  app:
    build: ./
    links:
    - redis
    command: ["--workers=5", "--iterations=500"]
    networks:
      node_net:
        ipv4_address: 172.28.1.3

networks:
  node_net:
    ipam:
      driver: default
      config:
      - subnet: 172.28.0.0/16
